#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from file1.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 10 "file1.y"

	#include <stdio.h>
	#include <bits/stdc++.h>
	using namespace std;
	typedef struct node
	{
		int h1,h2,max_path,mainflag;
		char name[50];
		int value;
		int size;
		struct node* child[10];
	}node;	
	int ifmax = 0,whmax =0,mainmax = 0;
	extern char* yytext;
	void DFS(node *root);
	node* root = NULL;
	node *mknode0(int s);
	node *mknode1(int s,node* c1);
	node *mknode2(int s,node *c1,node *c2);
	node *mknode3(int s,node *c1,node *c2,node *c3);
	node *mknode4(int s,node *c1,node *c2,node *c3,node *c4);
	node *mknode5(int s,node *c1,node *c2,node *c3,node *c4,node *c5);
	node *mknode6(int s,node *c1,node *c2,node *c3,node *c4,node *c5,node *c6);
	node *mknode7(int s,node *c1,node *c2,node *c3,node* c4,node *c5,node *c6,node *c7);
	void yyerror(string);
	int yylex(void);
	int debug = 1;
	int var_count = 0;
	int label_start = 0;
	map<string, int> var_offset;
	string data_buffer, code_buffer;
#define YYSTYPE struct node *

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	FLOAT_LITERAL	258
#define	INTEGER_LITERAL	259
#define	INT	260
#define	RETURN	261
#define	BREAK	262
#define	CONT	263
#define	VOID	264
#define	FLOAT	265
#define	WHILE	266
#define	IF	267
#define	PRINTF	268
#define	STRING	269
#define	IDENTIFIER	270
#define	ELSE	271
#define	OR	272
#define	EQ	273
#define	NEQ	274
#define	LEQ	275
#define	GEQ	276
#define	AND	277


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int FLOAT_LITERAL;
static const int INTEGER_LITERAL;
static const int INT;
static const int RETURN;
static const int BREAK;
static const int CONT;
static const int VOID;
static const int FLOAT;
static const int WHILE;
static const int IF;
static const int PRINTF;
static const int STRING;
static const int IDENTIFIER;
static const int ELSE;
static const int OR;
static const int EQ;
static const int NEQ;
static const int LEQ;
static const int GEQ;
static const int AND;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,FLOAT_LITERAL=258
	,INTEGER_LITERAL=259
	,INT=260
	,RETURN=261
	,BREAK=262
	,CONT=263
	,VOID=264
	,FLOAT=265
	,WHILE=266
	,IF=267
	,PRINTF=268
	,STRING=269
	,IDENTIFIER=270
	,ELSE=271
	,OR=272
	,EQ=273
	,NEQ=274
	,LEQ=275
	,GEQ=276
	,AND=277


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::FLOAT_LITERAL=258;
const int YY_parse_CLASS::INTEGER_LITERAL=259;
const int YY_parse_CLASS::INT=260;
const int YY_parse_CLASS::RETURN=261;
const int YY_parse_CLASS::BREAK=262;
const int YY_parse_CLASS::CONT=263;
const int YY_parse_CLASS::VOID=264;
const int YY_parse_CLASS::FLOAT=265;
const int YY_parse_CLASS::WHILE=266;
const int YY_parse_CLASS::IF=267;
const int YY_parse_CLASS::PRINTF=268;
const int YY_parse_CLASS::STRING=269;
const int YY_parse_CLASS::IDENTIFIER=270;
const int YY_parse_CLASS::ELSE=271;
const int YY_parse_CLASS::OR=272;
const int YY_parse_CLASS::EQ=273;
const int YY_parse_CLASS::NEQ=274;
const int YY_parse_CLASS::LEQ=275;
const int YY_parse_CLASS::GEQ=276;
const int YY_parse_CLASS::AND=277;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		156
#define	YYFLAG		-32768
#define	YYNTBASE	41

#define YYTRANSLATE(x) ((unsigned)(x) <= 277 ? yytranslate[x] : 70)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    39,     2,     2,     2,    38,    40,     2,    28,
    29,    27,    35,    24,    36,     2,    37,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    23,    33,
    32,    34,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    25,     2,    26,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    30,     2,    31,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     9,    11,    15,    20,    27,    35,
    37,    39,    41,    44,    47,    50,    57,    59,    60,    64,
    66,    69,    74,    77,    79,    81,    83,    85,    87,    89,
    91,    93,    95,   103,   109,   114,   117,   118,   122,   129,
   135,   143,   146,   150,   153,   156,   161,   169,   173,   177,
   181,   185,   189,   193,   197,   201,   205,   209,   213,   217,
   221,   224,   227,   230,   233,   236,   238,   243,   248,   250,
   252,   254,   258,   260,   262,   264,   266,   270,   272,   274
};

static const short yyrhs[] = {    42,
     0,    42,    43,     0,    43,     0,    44,     0,    46,     0,
    45,    66,    23,     0,    45,    66,    24,    44,     0,    45,
    66,    25,    64,    26,    23,     0,    45,    66,    25,    64,
    26,    24,    44,     0,     9,     0,     5,     0,    10,     0,
     9,    27,     0,     5,    27,     0,    10,    27,     0,    45,
    66,    28,    47,    29,    54,     0,    48,     0,     0,    48,
    24,    49,     0,    49,     0,    45,    66,     0,    45,    66,
    25,    26,     0,    50,    51,     0,    51,     0,    61,     0,
    54,     0,    57,     0,    53,     0,    58,     0,    59,     0,
    60,     0,    52,     0,    13,    28,    67,    24,    66,    29,
    23,     0,    11,    28,    62,    29,    51,     0,    30,    55,
    50,    31,     0,    55,    56,     0,     0,    45,    66,    23,
     0,    45,    66,    25,    62,    26,    23,     0,    12,    28,
    62,    29,    51,     0,    12,    28,    62,    29,    51,    16,
    51,     0,     6,    23,     0,     6,    62,    23,     0,     7,
    23,     0,     8,    23,     0,    66,    32,    62,    23,     0,
    66,    25,    62,    26,    32,    62,    23,     0,    63,    17,
    63,     0,    63,    18,    63,     0,    63,    19,    63,     0,
    63,    20,    63,     0,    63,    33,    63,     0,    63,    21,
    63,     0,    63,    34,    63,     0,    63,    22,    63,     0,
    63,    35,    63,     0,    63,    36,    63,     0,    63,    27,
    63,     0,    63,    37,    63,     0,    63,    38,    63,     0,
    39,    63,     0,    36,    63,     0,    35,    63,     0,    27,
    63,     0,    40,    63,     0,    63,     0,    66,    28,    69,
    29,     0,    66,    25,    62,    26,     0,    64,     0,    65,
     0,    66,     0,    28,    62,    29,     0,     4,     0,     3,
     0,    15,     0,    14,     0,    68,    24,    62,     0,    62,
     0,    68,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    46,    55,    61,    67,    73,    80,    89,    98,   112,   126,
   134,   141,   148,   157,   166,   176,   187,   193,   198,   206,
   212,   218,   228,   234,   240,   246,   251,   256,   261,   266,
   271,   276,   282,   297,   310,   321,   327,   332,   342,   356,
   368,   382,   392,   402,   413,   424,   435,   449,   458,   466,
   474,   482,   490,   498,   506,   514,   522,   530,   538,   546,
   554,   561,   568,   575,   582,   589,   595,   604,   614,   621,
   627,   633,   644,   654,   663,   672,   681,   689,   695,   701
};

static const char * const yytname[] = {   "$","error","$illegal.","FLOAT_LITERAL",
"INTEGER_LITERAL","INT","RETURN","BREAK","CONT","VOID","FLOAT","WHILE","IF",
"PRINTF","STRING","IDENTIFIER","ELSE","OR","EQ","NEQ","LEQ","GEQ","AND","';'",
"','","'['","']'","'*'","'('","')'","'{'","'}'","'='","'<'","'>'","'+'","'-'",
"'/'","'%'","'!'","'&'","program","decl_list","decl","var_decl","type_spec",
"func_decl","params","param_list","param","stmt_list","stmt","print_stmt","while_stmt",
"compound_stmt","local_decls","local_decl","if_stmt","return_stmt","break_stmt",
"continue_stmt","assign_stmt","expr","Pexpr","integerLit","floatLit","identifier",
"string","arg_list","args",""
};
#endif

static const short yyr1[] = {     0,
    41,    42,    42,    43,    43,    44,    44,    44,    44,    45,
    45,    45,    45,    45,    45,    46,    47,    47,    48,    48,
    49,    49,    50,    50,    51,    51,    51,    51,    51,    51,
    51,    51,    52,    53,    54,    55,    55,    56,    56,    57,
    57,    58,    58,    59,    60,    61,    61,    62,    62,    62,
    62,    62,    62,    62,    62,    62,    62,    62,    62,    62,
    62,    62,    62,    62,    62,    62,    62,    62,    63,    63,
    63,    63,    64,    65,    66,    67,    68,    68,    69,    69
};

static const short yyr2[] = {     0,
     1,     2,     1,     1,     1,     3,     4,     6,     7,     1,
     1,     1,     2,     2,     2,     6,     1,     0,     3,     1,
     2,     4,     2,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     7,     5,     4,     2,     0,     3,     6,     5,
     7,     2,     3,     2,     2,     4,     7,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     2,     2,     2,     2,     2,     1,     4,     4,     1,     1,
     1,     3,     1,     1,     1,     1,     3,     1,     1,     0
};

static const short yydefact[] = {     0,
    11,    10,    12,     1,     3,     4,     0,     5,    14,    13,
    15,     2,    75,     0,     6,     0,     0,    18,     7,     0,
    73,     0,     0,     0,    17,    20,     0,     0,    21,     0,
     0,     8,     0,     0,    37,    16,    19,     9,    22,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    24,    32,
    28,    26,    36,    27,    29,    30,    31,    25,     0,    74,
    42,     0,     0,     0,     0,     0,     0,     0,    66,    69,
    70,    71,    44,    45,     0,     0,     0,     0,    35,    23,
     0,     0,    64,    71,     0,    63,    62,    61,    65,    43,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    80,     0,     0,    76,     0,    38,
     0,     0,     0,    72,    48,    49,    50,    51,    53,    55,
    58,    52,    54,    56,    57,    59,    60,     0,    78,    79,
     0,     0,     0,     0,     0,     0,    46,    68,     0,    67,
    34,    40,     0,     0,     0,    77,     0,     0,    39,     0,
    41,    33,    47,     0,     0,     0
};

static const short yydefgoto[] = {   154,
     4,     5,     6,     7,     8,    24,    25,    26,    48,    49,
    50,    51,    52,    40,    53,    54,    55,    56,    57,    58,
    68,    69,    70,    71,    84,   109,   130,   131
};

static const short yypact[] = {    27,
   -23,     8,    11,    27,-32768,-32768,     3,-32768,-32768,-32768,
-32768,-32768,-32768,    30,-32768,    27,    25,    27,-32768,     3,
-32768,    16,     3,   -10,    21,-32768,    42,   -12,    32,    19,
    27,-32768,    27,    35,-32768,-32768,-32768,-32768,-32768,   152,
    24,    39,    47,    43,    44,    45,     3,   162,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -22,-32768,
-32768,     2,   116,     2,     2,     2,     2,    53,   177,-32768,
-32768,    -2,-32768,-32768,   116,   116,    69,    23,-32768,-32768,
   116,   116,-32768,-32768,    58,-32768,-32768,-32768,-32768,-32768,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,   116,   116,    59,    60,-32768,    66,-32768,
   116,    65,    70,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    68,-32768,    71,
    63,   172,   172,     3,    73,    64,-32768,-32768,   116,-32768,
-32768,    85,    74,    79,   116,-32768,   172,    82,-32768,    98,
-32768,-32768,-32768,   122,   123,-32768
};

static const short yypgoto[] = {-32768,
-32768,   120,    -8,    -9,-32768,-32768,-32768,    97,-32768,   -47,
-32768,-32768,    99,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   -61,    15,   113,-32768,    -7,-32768,-32768,-32768
};


#define	YYLAST		215


static const short yytable[] = {    14,
    80,    85,    81,     9,    60,    21,    20,    19,    23,    82,
    32,    33,    27,   106,   107,    29,    13,    13,    30,   112,
   113,    23,   104,    20,    38,   105,    60,    21,    21,    63,
    47,     1,    59,    72,    10,     2,     3,    11,    13,    78,
    59,    28,   128,   129,    31,   110,    61,   111,    35,   135,
    62,    63,    15,    16,    17,    72,    34,    18,    64,    65,
    39,    73,    66,    67,    15,    16,    17,    72,    72,    74,
    75,    76,    77,    72,    72,    90,    83,   146,    86,    87,
    88,    89,   108,   150,   141,   142,   114,   132,   133,   134,
   136,   140,   137,   138,   139,   145,    72,    72,   144,   151,
   147,   149,   148,    72,   152,   115,   116,   117,   118,   119,
   120,   121,   122,   123,   124,   125,   126,   127,    60,    21,
   153,   155,   156,    12,    59,    59,   143,    37,    36,    22,
    13,    72,     0,     0,     0,     0,     0,    72,     0,    59,
     0,     0,    62,    63,     0,     0,     0,     0,     0,     0,
    64,    65,     0,     0,    66,    67,     1,    41,    42,    43,
     2,     3,    44,    45,    46,     0,    13,    41,    42,    43,
     0,     0,    44,    45,    46,     0,    13,    41,    42,    43,
     0,    35,    44,    45,    46,     0,    13,     0,     0,     0,
     0,    35,    79,    91,    92,    93,    94,    95,    96,     0,
     0,    35,     0,    97,     0,     0,     0,     0,     0,    98,
    99,   100,   101,   102,   103
};

static const short yycheck[] = {     7,
    48,    63,    25,    27,     3,     4,    16,    16,    18,    32,
    23,    24,    20,    75,    76,    23,    15,    15,    29,    81,
    82,    31,    25,    33,    33,    28,     3,     4,     4,    28,
    40,     5,    40,    41,    27,     9,    10,    27,    15,    47,
    48,    26,   104,   105,    24,    23,    23,    25,    30,   111,
    27,    28,    23,    24,    25,    63,    25,    28,    35,    36,
    26,    23,    39,    40,    23,    24,    25,    75,    76,    23,
    28,    28,    28,    81,    82,    23,    62,   139,    64,    65,
    66,    67,    14,   145,   132,   133,    29,    29,    29,    24,
    26,    29,    23,    26,    24,    32,   104,   105,    26,   147,
    16,    23,    29,   111,    23,    91,    92,    93,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,     3,     4,
    23,     0,     0,     4,   132,   133,   134,    31,    30,    17,
    15,   139,    -1,    -1,    -1,    -1,    -1,   145,    -1,   147,
    -1,    -1,    27,    28,    -1,    -1,    -1,    -1,    -1,    -1,
    35,    36,    -1,    -1,    39,    40,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    -1,    15,     6,     7,     8,
    -1,    -1,    11,    12,    13,    -1,    15,     6,     7,     8,
    -1,    30,    11,    12,    13,    -1,    15,    -1,    -1,    -1,
    -1,    30,    31,    17,    18,    19,    20,    21,    22,    -1,
    -1,    30,    -1,    27,    -1,    -1,    -1,    -1,    -1,    33,
    34,    35,    36,    37,    38
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 48 "file1.y"
{
		
		yyval = mknode1(1,yyvsp[0]);
		root = yyval;
		strcpy(yyval->name,"program");
	;
    break;}
case 2:
#line 57 "file1.y"
{
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"decl_list");
	;
    break;}
case 3:
#line 62 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"decl_list");
	;
    break;}
case 4:
#line 69 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"decl");
	;
    break;}
case 5:
#line 74 "file1.y"
{
		
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"decl");
	;
    break;}
case 6:
#line 82 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode3(3,yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"var_decl");		
		
	;
    break;}
case 7:
#line 90 "file1.y"
{

		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,";");
		yyval = mknode4(4,yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"var_decl");
		
	;
    break;}
case 8:
#line 99 "file1.y"
{	

		
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"[");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"]");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode6(6,yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"var_decl");
		if(debug) cout<<"declared[]"<<yyvsp[-4]->name<<endl;				
	;
    break;}
case 9:
#line 113 "file1.y"
{

		yyvsp[-4] = mknode0(0);
		strcpy(yyvsp[-4]->name,"[");
		yyvsp[-2] = mknode0(0);
		strcpy(yyvsp[-2]->name,"]");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,",");
		yyval = mknode7(7,yyvsp[-6],yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"var_decl");
		if(debug) cout<<"declared [],"<<yyvsp[-5]->name<<endl;				
	;
    break;}
case 10:
#line 128 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"VOID");
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"type_spec");
	;
    break;}
case 11:
#line 135 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"INT");
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"type_spec");
	;
    break;}
case 12:
#line 142 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"FLOAT");
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"type_spec");
	;
    break;}
case 13:
#line 149 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"VOID");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"*");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"type_spec");
	;
    break;}
case 14:
#line 158 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"INT");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"*");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"type_spec");
	;
    break;}
case 15:
#line 167 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"FLOAT");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"*");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"type_spec");
	;
    break;}
case 16:
#line 178 "file1.y"
{
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"(");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,")");
		yyval= mknode6(6,yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"func_decl");
	;
    break;}
case 17:
#line 189 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"params");
	;
    break;}
case 18:
#line 193 "file1.y"
{
		yyval = mknode0(1);
		strcpy(yyval->name,"params");
	;
    break;}
case 19:
#line 200 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,",");
		yyval = mknode3(3,yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"param_list");
	;
    break;}
case 20:
#line 207 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"param_list");
	;
    break;}
case 21:
#line 214 "file1.y"
{
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"param");
	;
    break;}
case 22:
#line 219 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"[");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"]");
		yyval = mknode4(4,yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"param");
	;
    break;}
case 23:
#line 230 "file1.y"
{
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"stmt_list");
	;
    break;}
case 24:
#line 235 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt_list");
	;
    break;}
case 25:
#line 242 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 26:
#line 247 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 27:
#line 252 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 28:
#line 257 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 29:
#line 262 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 30:
#line 267 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 31:
#line 272 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");
	;
    break;}
case 32:
#line 277 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"stmt");

	;
    break;}
case 33:
#line 284 "file1.y"
{
		yyvsp[-6] = mknode0(0);
		yyvsp[-5] = mknode0(0);

		yyvsp[-3] = mknode0(0);
				
		yyvsp[-1] = mknode0(0);
		yyvsp[0] = mknode0(0);

		yyval = mknode7(6,yyvsp[-6],yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);		
		strcpy(yyval->name,"print_stmt");

	;
    break;}
case 34:
#line 299 "file1.y"
{
		yyvsp[-4] = mknode0(0);
		strcpy(yyvsp[-4]->name,"WHILE");
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"(");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,")");
		yyval = mknode5(5,yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"while_stmt");
	;
    break;}
case 35:
#line 312 "file1.y"
{
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"{");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,"}");
		yyval = mknode4(4,yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"compound_stmt");
	;
    break;}
case 36:
#line 323 "file1.y"
{
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"local_decls");
	;
    break;}
case 37:
#line 327 "file1.y"
{
		yyval = mknode0(1);
		strcpy(yyval->name,"local_decls");
	;
    break;}
case 38:
#line 334 "file1.y"
{
//		cout<<"declared "<<$2->name<<"\n";
		
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode3(3,yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"local_decl");
	;
    break;}
case 39:
#line 343 "file1.y"
{

				
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"[");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"]");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode6(6,yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"local_decl");
	;
    break;}
case 40:
#line 358 "file1.y"
{
		yyvsp[-4] = mknode0(0);
		strcpy(yyvsp[-4]->name,"IF");
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"(");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,")");
		yyval = mknode5(5,yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"if_stmt");
	;
    break;}
case 41:
#line 369 "file1.y"
{
		yyvsp[-6] = mknode0(0);
		strcpy(yyvsp[-6]->name,"IF");
		yyvsp[-5] = mknode0(0);
		strcpy(yyvsp[-5]->name,"(");
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,")");
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"ELSE");
		yyval = mknode7(7,yyvsp[-6],yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"if_stmt");
	;
    break;}
case 42:
#line 384 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"RETURN");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"return_stmt");
	;
    break;}
case 43:
#line 393 "file1.y"
{
		yyvsp[-2] = mknode0(0);
		strcpy(yyvsp[-2]->name,"RETURN");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode3(3,yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"return_stmt");
	;
    break;}
case 44:
#line 404 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"BREAK");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"break_stmt");
	;
    break;}
case 45:
#line 415 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"CONT");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"continue_stmt");
	;
    break;}
case 46:
#line 426 "file1.y"
{
		yyvsp[-2] = mknode2(2,yyvsp[-3],yyvsp[-1]);
		strcpy(yyvsp[-2]->name,"=");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyval = mknode2(2,yyvsp[-2],yyvsp[0]);
		
		strcpy(yyval->name,"assign_stmt");
	;
    break;}
case 47:
#line 436 "file1.y"
{
		yyvsp[-5] = mknode0(0);
		strcpy(yyvsp[-5]->name,"[");
		yyvsp[-3] = mknode0(0);
		strcpy(yyvsp[-3]->name,"]");
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,";");
		yyvsp[-2] = mknode5(5,yyvsp[-6],yyvsp[-5],yyvsp[-4],yyvsp[-3],yyvsp[-1]);
		strcpy(yyvsp[-2]->name,"=");
		yyval = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyval->name,"assign_stmt");
	;
    break;}
case 48:
#line 451 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"OR");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value || yyvsp[0]->value;
	;
    break;}
case 49:
#line 459 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"EQ");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value == yyvsp[0]->value;
	;
    break;}
case 50:
#line 467 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"NEQ");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value != yyvsp[0]->value;
	;
    break;}
case 51:
#line 475 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"LEQ");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value <= yyvsp[0]->value;
	;
    break;}
case 52:
#line 483 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"<");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value < yyvsp[0]->value;
	;
    break;}
case 53:
#line 491 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"GEQ");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value >= yyvsp[0]->value;
	;
    break;}
case 54:
#line 499 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,">");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value > yyvsp[0]->value;
	;
    break;}
case 55:
#line 507 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"AND");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value && yyvsp[0]->value;
	;
    break;}
case 56:
#line 515 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"+");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value + yyvsp[0]->value;
	;
    break;}
case 57:
#line 523 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"-");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value - yyvsp[0]->value;
	;
    break;}
case 58:
#line 531 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"*");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value + yyvsp[0]->value;
	;
    break;}
case 59:
#line 539 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"/");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value / yyvsp[0]->value;
	;
    break;}
case 60:
#line 547 "file1.y"
{
		yyvsp[-1] = mknode2(2,yyvsp[-2],yyvsp[0]);
		strcpy(yyvsp[-1]->name,"%");
		yyval = mknode1(1,yyvsp[-1]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[-2]->value % yyvsp[0]->value;
	;
    break;}
case 61:
#line 555 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"!");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 62:
#line 562 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"-");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 63:
#line 569 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"+");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 64:
#line 576 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"*");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 65:
#line 583 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,"&");
		yyval = mknode2(2,yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 66:
#line 590 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"expr");
		yyval->value = yyvsp[0]->value;
	;
    break;}
case 67:
#line 596 "file1.y"
{
		yyvsp[-2] = mknode0(0);
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[-2]->name,"(");
		strcpy(yyvsp[0]->name,")");			
		yyval = mknode4(4,yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 68:
#line 605 "file1.y"
{
		yyvsp[-2] = mknode0(0);
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[-2]->name,"[");
		strcpy(yyvsp[0]->name,"]");
		yyval = mknode4(4,yyvsp[-3],yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"expr");
	;
    break;}
case 69:
#line 616 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"Pexpr");
		yyval->value = yyvsp[0]->value;
	;
    break;}
case 70:
#line 622 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"Pexpr");
		yyval->value = yyvsp[0]->value;
	;
    break;}
case 71:
#line 628 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"Pexpr");
		yyval->value = yyvsp[0]->value;
	;
    break;}
case 72:
#line 634 "file1.y"
{
		yyvsp[-2] = mknode0(0);
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[-2]->name,"(");
		strcpy(yyvsp[0]->name,")");
		yyval = mknode3(3,yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"Pexpr");
		yyval->value = yyvsp[-1]->value;
	;
    break;}
case 73:
#line 646 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,yytext);
		yyval = mknode1(1,yyvsp[0]);
		yyval->value = atoi(yytext);
		strcpy(yyval->name,"integerLit");	
	;
    break;}
case 74:
#line 656 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,yytext);
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"floatLit");
	;
    break;}
case 75:
#line 665 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,yytext);
		yyval = mknode1(1,yyvsp[0]);

		strcpy(yyval->name,"identifier");
	;
    break;}
case 76:
#line 674 "file1.y"
{
		yyvsp[0] = mknode0(0);
		strcpy(yyvsp[0]->name,yytext);
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"string");
	;
    break;}
case 77:
#line 683 "file1.y"
{
		yyvsp[-1] = mknode0(0);
		strcpy(yyvsp[-1]->name,",");
		yyval = mknode3(3,yyvsp[-2],yyvsp[-1],yyvsp[0]);
		strcpy(yyval->name,"arg_list");
	;
    break;}
case 78:
#line 690 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"arg_list");
	;
    break;}
case 79:
#line 697 "file1.y"
{
		yyval = mknode1(1,yyvsp[0]);
		strcpy(yyval->name,"args");
	;
    break;}
case 80:
#line 701 "file1.y"
{
		yyval = mknode0(1);
		strcpy(yyval->name,"args");
	;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 708 "file1.y"


void yyerror(string s) {
    printf("Invalid Input\n");
	exit(0);
}

void print(node* root, int l){
	cout<<root->name<<" "<<l<<endl;
	for(int i=0; i < (root->size); ++i){
		print(root->child[i], l+1);
	}
}

void print_init(){
cout<<"	.file	\"hello.c\"\n";
cout<<"	.section	.rodata\n";
cout<<".LC0:\n";
cout<<"	.string	\"%d\\n\"\n";
cout<<"	.text\n";
cout<<"	.globl	main\n";
cout<<"	.type	main, @function\n";
cout<<"main:\n";
cout<<"	pushq	%rbp\n";
cout<<"	movq	%rsp, %rbp\n";
cout<<" subq $4000, %rsp\n";
}

void print_end(){

cout<<"\tleave\n";
cout<<"\tret\n";
cout<<"\t.size	main, .-main\n";
cout<<"\t.ident	\"GCC: (Debian 4.9.2-10) 4.9.2\"\n";
cout<<"\t.section	.note.GNU-stack,\"\",@progbits\n";

}

int main()
{
	//extern int yydebug;yydebug = 1;	
	yyparse();
	print_init();
	if(root != NULL)
	{	
		DFS(root);
	}	
	else
	{
		return 0;
	}

	//print(root, 0);
	print_end();
	return 0;
}


void expression_eval(node *root){

	for(int i=0; i<root->size; ++i){
		expression_eval(root->child[i]);
	}

	if(strcmp(root->name, "integerLit") == 0 ){

		cout<<"\tpushq\t$"<<atoi((root->child[0])->name)<<"\n";  
	}
	if(strcmp(root->name,"identifier") == 0  ){

		cout<<"\tpushq\t"<<-4*var_offset[(root->child[0])->name]<<"(%rbp)\n"; 

	}
	if( (strcmp(root->name,"expr") == 0) && root->size == 1  ){
	
		if(strcmp (root->child[0]->name, "+") == 0 ){
			//addition
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";	
				cout<<"\taddl\t%ebx, %eax\n";
			cout<<"\tpushq\t%rax\n";

		}

		if(strcmp(root->child[0]->name, "-") == 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tsubl\t%ebx, %eax\n";
			cout<<"\tpushq\t%rax\n";
		}
		if(strcmp(root->child[0]->name, "*")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\timull\t%ebx, %eax\n";
			cout<<"\tpushq\t%rax\n";
		}
		if(strcmp(root->child[0]->name, "/")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcltd\n";
				cout<<"\tidivl\t%ebx\n";
			cout<<"\tpushq\t%rax\n";
		}
		if(strcmp(root->child[0]->name , "%")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcltd\n";
				cout<<"\tidivl\t%ebx\n";
				cout<<"\tmovl\t%ebx, %eax\n";
			cout<<"\tpushq\t%rax\n";
		}
		if(strcmp(root->child[0]->name , "OR")== 0){

			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
			
			cout<<"\tcmpl $0, %eax\n";
			cout<<"jne\t.L"<<label_start<<"\n";
			cout<<"\tcmpl $0, %ebx\n";
			cout<<"je\t.L"<<label_start+1<<"\n";
		cout<<".L"<<label_start<<":\n";
			cout<<"\tmovl\t$1, %eax\n";
			cout<<"\tjmp\t.L"<<label_start+2<<"\n";
		cout<<".L"<<label_start+1<<":\n";
			cout<<"\tmovl $0, %eax\n";
		cout<<".L"<<label_start+2<<":\n";			
			cout<<"\tpushq\t%rax\n";	
			label_start += 3;
			
		}
		if(strcmp(root->child[0]->name , "AND")== 0){
			
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
			
			cout<<"\tcmp $0, %eax\n";
			cout<<"je\t.L"<<label_start<<"\n";
			cout<<"\tcmp $0, %ebx\n";
			cout<<"je\t.L"<<label_start<<"\n";
			cout<<"\tmovl\t$1, %eax\n";
			cout<<"\tjmp\t.L"<<label_start+1<<"\n";
		cout<<".L"<<label_start<<":\n";
			cout<<"\tmovl $0, %eax\n";
		cout<<".L"<<label_start+1<<":\n";			
			cout<<"\tpushq\t%rax\n";	
			label_start += 2;
		}
		if(strcmp(root->child[0]->name , "NEQ")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcmpl\t%ebx, %eax\n";
			cout<<"\tsetne\t%al\n";
			cout<<"\tpushq\t%rax\n";	
		}
		if(strcmp(root->child[0]->name , "EQ")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcmpl\t%ebx, %eax\n";
			cout<<"\tsete\t%al\n";
			cout<<"\tpushq\t%rax\n";	
		}
		if(strcmp(root->child[0]->name , "LEQ")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcmpl\t%ebx, %eax\n";
			cout<<"\tsetle\t%al\n";
			cout<<"\tpushq\t%rax\n";	
		}
		if(strcmp(root->child[0]->name , "GEQ")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcmpl\t%ebx, %eax\n";
			cout<<"\tsetge\t%al\n";
			cout<<"\tpushq\t%rax\n";
		}
		if(strcmp(root->child[0]->name , "<")== 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcmpl\t%ebx, %eax\n";
			cout<<"\tsetl\t%al\n";
			cout<<"\tpushq\t%rax\n";	
		}
		if(strcmp(root->child[0]->name , ">") == 0){
			cout<<"\tpop\t%rbx\n";
			cout<<"\tpop\t%rax\n";
				cout<<"\tcmpl\t%ebx, %eax\n";
			cout<<"\tsetg\t%al\n";
			cout<<"\tpushq\t%rax\n";	
		}

		//if epxr -> Pexpr 
	}

	if( (strcmp(root->name,"expr") == 0) && root->size == 2  ){
		//!P -P +P *P &P
		if(strcmp(root->child[0]->name, "!")  == 0){
			/*
			cmpl	$0, -4(%rbp)
			sete	%al
			movzbl	%al, %eax
			movl	%eax, -12(%rbp)
			*/
			cout<<"\tpop\t%rbx\n";
			cout<<"\tcmpl\t$0, %ebx\n";
			cout<<"\tsete %al\n";
			cout<<"\tmovzbl\t%al, %eax\n";
			cout<<"\tpushq\t%rax\n";
		}
		if(strcmp(root->child[0]->name, "-")  == 0){
			/*
	movl	-4(%rbp), %eax
	negl	%eax
	movl	%eax, -12(%rbp)
			*/
			cout<<"\tpop\t%rax\n";
			cout<<"\tnegl %eax\n";
			cout<<"\tpushq\t%rax\n";	
		}
	}

}

void DFS(node *root)
{

	int num = root->size;
	int i;
	for(i=0;i<num;i++)
	{
//		if(strcmp(root->name,"assign_stmt") == 0 && i==0 ){ continue; }

		DFS(root->child[i]);
	}


	if(strcmp(root->name,"print_stmt") == 0)
	{
	/*
		movl	-4(%rbp), %eax
		movl	%eax, %esi
		movl	$.LC0, %edi
		movl	$0, %eax
	*/

		cout<<"\tmovl\t"<<var_offset[(root->child[4])->child[0]->name]*(-4)<<"(%rbp), %eax\n";
		cout<<"\tmovl\t%eax, %esi\n";
		cout<<"\tmovl\t$.LC0"<<", %edi\n";
		cout<<"\tmovl\t$0, \t"<<"%eax\n";
		cout<<"\tcall\tprintf\n";		
		
	}
	if(strcmp(root->name,"local_decl") == 0)
	{
		var_offset[root->child[1]->child[0]->name] = (++var_count);
	}

	if(strcmp(root->name,"assign_stmt") == 0)
	{
		expression_eval(root->child[0]->child[1]);
		//rbx == rax
		cout<<"\tpop\t%rbx\n";	
		cout<<"\tmovl\t %ebx, ";

		cout<<var_offset[root->child[0]->child[0]->child[0]->name]*-4<<"(%rbp)"<<endl;

	}



	return;
}

node *mknode7(int s,node *c1,node *c2,node *c3,node* c4,node *c5,node *c6,node *c7)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->child[1] = c2;
	nn->child[2] = c3;
	nn->child[3] = c4;
	nn->child[4] = c5;
	nn->child[5] = c6;
	nn->child[6] = c7;
	nn->size = 7;
	return nn;
}

node *mknode6(int s,node *c1,node *c2,node *c3,node* c4,node *c5,node *c6)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->child[1] = c2;
	nn->child[2] = c3;
	nn->child[3] = c4;
	nn->child[4] = c5;
	nn->child[5] = c6;
	nn->size = 6;
	return nn;
}

node *mknode5(int s,node *c1,node *c2,node *c3,node* c4,node *c5)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->child[1] = c2;
	nn->child[2] = c3;
	nn->child[3] = c4;
	nn->child[4] = c5;
	nn->size = 5;
	return nn;
}

node *mknode4(int s,node *c1,node *c2,node *c3,node* c4)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->child[1] = c2;
	nn->child[2] = c3;
	nn->child[3] = c4;
	nn->size = 4;
	return nn;
}

node *mknode3(int s,node *c1,node *c2,node *c3)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->child[1] = c2;
	nn->child[2] = c3;
	nn->size = 3;
	return nn;
}

node *mknode2(int s,node *c1,node *c2)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->child[1] = c2;
	nn->size = 2;
	return nn;
}

node *mknode1(int s,node *c1)
{
	node* nn = (node *)malloc(sizeof(node));
	nn->child[0] = c1;
	nn->size = 1;
	return nn;
}

node *mknode0(int s)
{
	node* nn = (node *)malloc(sizeof(node));
	if(s == 0)
	{
		nn->size = 0;
	}
	if(s == 1)
	{
		node* nnc = (node *)malloc(sizeof(node));
		nnc->size = 0;
		strcpy(nnc->name,"#EPS");
		nn->child[0] = nnc;
		nn->size = 1;
	}
	return nn;
}
